// <auto-generated />
namespace General_Store.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FirstMigrate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstMigrate));
        
        string IMigrationMetadata.Id
        {
            get { return "202012051627342_FirstMigrate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
